version: '3'
volumes: 
  dados:
networks:
  banco:
  web:    
  fila:
services:
  db: 
    image: postgres:9.6
    volumes: 
        - dados:/var/lib/postgresql/data #volume dos dados
        - ./scripts:/scripts #scripts
        - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - banco    
    environment: 
      POSTGRES_DB: 'db'
      POSTGRES_PASSWORD: somepassword
      POSTGRES_HOST_AUTH_METHOD: 'trust'
  frontend:
    image: nginx:1.13
    volumes: 
        - ./web:/usr/share/nginx/html #site
        - ./nginx/default.conf:/etc/nginx/conf.d/default.conf #configurcao do proxy reverso
    ports: 
        - 80:80   
    networks:
        - web   
    depends_on:
        - app   
  app:
     image: python:3.6 
     volumes: 
        - ./app:/app #aplicação        
     working_dir: /app
     command: bash ./app.sh
     networks:
      - banco
      - web
      - fila
     depends_on:
      - db
      - queue
     environment:
      - DB_NAME=abc_sender #nome correto do banco no  arquivo  'docker-compose.override.yml' 
  queue:
     image: redis:3.2
     networks:
      - fila
  worker:
    build: worker
    volumes:
      # Worker
      - ./worker:/worker
    working_dir: /worker
    command: worker.py
    networks:
      - fila
    depends_on:
      - queue    

    